"""Add type column to Tool and McpServer tables

Revision ID: 1f6e5d7405fa
Revises: afb79a3a5c7a
Create Date: 2025-09-12 21:40:00.942968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f6e5d7405fa'
down_revision: Union[str, Sequence[str], None] = 'afb79a3a5c7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mcp_servers', sa.Column('type', sa.String(), nullable=True))
    op.create_index(op.f('ix_mcp_servers_type'), 'mcp_servers', ['type'], unique=False)
    op.add_column('tools', sa.Column('type', sa.String(), nullable=True))
    op.create_index(op.f('ix_tools_type'), 'tools', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tools_type'), table_name='tools')
    op.drop_column('tools', 'type')
    op.drop_index(op.f('ix_mcp_servers_type'), table_name='mcp_servers')
    op.drop_column('mcp_servers', 'type')
    # ### end Alembic commands ###
